#pragma once

enum InitErrorCode : int
{
	MHSERVICE_INIT_SUCCESS = 0,
	GAME_MANAGER_INIT_FAIL = 1,
	DEVICE_MANAGER_INIT_FAIL = 2,
	MEMORY_ALLOC_FAIL = 3,
	DLL_LOAD_FAIL = 4,
	NETWORK_MANAGER_INIT_FAIL = 5,
	INVALID_SDK_PATH = 6,
	MOTIONHOUSE_SDK_ALREADY_INITIALIZED = 7,
	MOTIONHOUSE_SDK_ALREADY_DESTROYED = 8,
	MOTIONHOUSE_SDK_NOT_INITIALIZED = 9,
	EXCEPTION_OCCUR_IN_INITIALIZING = 10,
	DEVICE_PARAM_UPDATED_REQUEST_ALL_DEVICE_POWER_RESTART = 11,
};


enum MOTIONHOUSE_SDK_MODE
{
	SDK_MODE_DLL = 0,
	SDK_MODE_SENDER,
	SDK_MODE_RECEIVER,
};


enum
{
	MOTION_DATA_MIN = 0,
	MOTION_DATA_ROLL = 0,
	MOTION_DATA_PITCH = 1,
	MOTION_DATA_SWAY = 2,
	MOTION_DATA_SURGE = 3,
	MOTION_DATA_HEAVE = 4,
	MOTION_DATA_TRACTION_LOSS = 5,
	MOTION_DATA_6DOF = 6,
	MOTION_DATA_SUSPENSION_FR = 6,
	MOTION_DATA_SUSPENSION_FL = 7,
	MOTION_DATA_SUSPENSION_RR = 8,
	MOTION_DATA_SUSPENSION_RL = 9,
	MOTION_DATA_SUSPENSION_ROLL = 10,
	MOTION_DATA_SUSPENSION_PITCH = 11,
	MOTION_DATA_MAX,
};


enum GameId
{
	GAME_ID_NONE = 0
	, GAME_ASSETTO_CORSA
	, GAME_IRACING
	, GAME_EURO_TRUCK2
	, GAME_LIVE_FOR_SPEED
	, GAME_DIRT_3
	, GAME_RACE_07
	, GAME_F1_2014
	, GAME_DIRT_SHOWDOWN
	, GAME_GRID_AUTOSPORT
	, GAME_RFACTOR2
	, GAME_THE_CREW
	, GAME_DIRT_RALLY
	, GAME_PROJECT_CARS
	, GAME_R3E
	, GAME_RBR
	, GAME_GTA5
	, GAME_FSX
	, GAME_DCS
	, GAME_WAR_THUNDER
	, GAME_DIRT_2
	, GAME_XPLANE10
	, GAME_FALCON_BMS
	, GAME_AMERICAN_TRUCK
	, CONSOLE_PROJECT_CARS
	, GAME_RFACTOR
	, GAME_AUTOMOBILISTA
	, GAME_GRID
	, GAME_GRID2
	, GAME_NO_LIMIT2
	, GAME_F1_2013
	, GAME_USER_PROGRAM_FROM_MEMORY							//USER_PROGRAM_FROM_SHARED_MEMORY과 같은 값일 것
	, GAME_USER_PROGRAM_FROM_NETWORK						//USER_PROGRAM_FROM_NETWORK 과 같은 값일 것
	, GAME_USER_PROGRAM_FROM_DLL
	, GAME_F1_2015
	, GAME_F1_2016
	, CONSOLE_F1_2016
	, GAME_AEROFLY_FS2
	, CONSOLE_ASSETTOCORSA
	, GAME_UCWIN_ROAD
	, GAME_DIRT_4
	, GAME_XPLANE11
	, GAME_PREPAR3DV4
	, GAME_SPEEDBOAT
	, GAME_F1_2017
	, CONSOLE_F1_2017
	, GAME_F1_2012
	, GAME_PROJECT_CARS2
	, CONSOLE_PROJECT_CARS2
	, GAME_GRALLY
	, GAME_PRESCAN
	, GAME_FM7
	, CONSOLE_FM7
	, GAME_THE_CREW2
	, GAME_F1_2018
	, CONSOLE_F1_2018
	, GAME_ASSETTO_CORSA_COMPETIZIONE
	, GAME_MXBIKE
	, GAME_DIRT_RALLY2
	, GAME_RED_ROVER
	, GAME_MUD_RUNNER
	, GAME_FH4
	, CONSOLE_FH4
	, GAME_KARTKRAFT
	, GAME_RDS
	, GAME_F1_2019
	, CONSOLE_F1_2019
	, GAME_BEAMNG_DRIVE
	, GAME_HYPER_STORM
	, GAME_GRID_2019
	, GAME_TOURING_KARTS
	, GAME_RDR2
	, GAME_AUTOMOBILISTA2
	, GAME_FERNBUS
	, GAME_F1_2020
	, CONSOLE_F1_2020
	, GAME_VRACER_HOVERBIKE
	, GAME_MS_FSX_2020
	, GAME_PROJECT_CARS3
	, CONSOLE_PROJECT_CARS3
	, GAME_WRC_7
	, GAME_WRC_8
	, GAME_WRC_9
	, GAME_AIR_SIM
	, GAME_F1_2021
	, CONSOLE_F1_2021
	, GAME_WRC_10
	, GAME_VECTOR36
	, GAME_THE_BUS
	, GAME_FH5
	, CONSOLE_FH5
	, GAME_GRID_LEGENDS
	, CONSOLE_SPACE_MONKEY
	, GAME_F1_2022
	, CONSOLE_F1_2022
	, CONSOLE_GT
	, GAME_CAR_MAKER
	, GAME_WRC_GENERATIONS
	, GAME_F1_2023
    , CONSOLE_F1_2023
	, GAME_ID_MAX,
};


enum DeviceType
{
	DEVICE_TYPE_ALL = -1,
	DEVICE_TYPE_NONE = 0,
	DEVICE_TYPE_MH_CAC_STEWART_PLATFORM_TEST,
	DEVICE_TYPE_MH_CAC_4UN_VER3_5MM,
	DEVICE_TYPE_MH_CAC_3GEAR_60,
	DEVICE_TYPE_MH_CAC_2DOF_2,
	DEVICE_TYPE_MH_CAC_2DOF_5MM,
	DEVICE_TYPE_MH_CAC_3DOF_5MM,
	DEVICE_TYPE_MH_CAC_4DOF_5MM,
	DEVICE_TYPE_MH_CAC_1DOF_PRESS,
	DEVICE_TYPE_MH_CAC_1DOF_LADDER,
	DEVICE_TYPE_MH_CAC_MOTION_2DOF,
	DEVICE_TYPE_MH_CAC_4CYLINDER_1GEAR,
	DEVICE_TYPE_MH_CAC_RD_3DOF,						//Rasing duck, 3dof seat simulator
	DEVICE_TYPE_MH_AC_MOTION_3DOF_GEARS_60_750W,
	DEVICE_TYPE_MH_CAC_SURGE_TL,
	DEVICE_TYPE_MH_CAC_4UN_TL,
	DEVICE_TYPE_MH_CAC_4UN_VER3,
	DEVICE_TYPE_MH_CAC_2UN_VER3,
	DEVICE_TYPE_MH_CAC_SURGE_TL_VER2,
	DEVICE_TYPE_MH_BELT_TENSIONER,
	DEVICE_TYPE_MH_CAC_2GEAR_1GEAR,
	DEVICE_TYPE_MH_STEP_MOTION_2DOF,
	DEVICE_TYPE_MH_TORQUE_CONTROLLER,
	DEVICE_TYPE_MH_STEP_MOTION_4DOF,
	DEVICE_TYPE_SLI,
	DEVICE_TYPE_MH_CAC_3AXIS_MLINE_STAND,		//M-Line 3 axis, cylinder, 150mm stroke, 5mm lead, 400w 17bit, 2023.06.15
	DEVICE_TYPE_MH_STEP_MOTION_4DOF_TRACTION_LOSS,
	DEVICE_TYPE_MH_AC_MOTION_2DOF_FLIGHT_5MM,
	DEVICE_TYPE_MH_CAC_6AXIS_HDI,
	DEVICE_TYPE_MH_CAC_1DOF_TEST,
	DEVICE_TYPE_MH_AC_MOTION_4DOF,
	DEVICE_TYPE_MH_WIND_GENERATOR,
	DEVICE_TYPE_MH_CAC_6AXIS_RD,
	DEVICE_TYPE_MH_CAC_1AXIS_RD_STEP,
	DEVICE_TYPE_MH_AC_MOTION_6DOF,
	DEVICE_TYPE_MH_CAC_2AXIS_ACCIDENTAL_FALL,
	DEVICE_TYPE_MH_AC_MOTION_6DOF_CUSTOM,			//Treeze
	DEVICE_TYPE_MH_AC_MOTION_5DOF,
	DEVICE_TYPE_MH_AC_MOTION_4DOF_5MM,
	DEVICE_TYPE_MH_WIND_GENERATOR_V2,
	DEVICE_TYPE_MH_CAC_MOTION_4DOF,
	DEVICE_TYPE_MH_CAC_6UN,
	DEVICE_TYPE_MH_CAC_MOTION_2U,
	DEVICE_TYPE_MH_AC_MOTION_4DOF_TRACTION_LOSS,
	DEVICE_TYPE_MH_STEP_MOTION_5DOF,
	DEVICE_TYPE_MH_AC_MOTION_3DOFB,
	DEVICE_TYPE_MH_CAC_2UN_VER2,
	DEVICE_TYPE_MH_CAC_4UN_VER2,
	DEVICE_TYPE_MH_CAC_4UN_VER2_5MM,
	DEVICE_TYPE_MH_CAC_3DOF_GEARS_NOVATECH,		//Nova tech, 2 persons, 3gears,  2023.06.15
	DEVICE_TYPE_MH_AC_MOTION_3DOF_GEARS,	//M-Line old 3gear box simulator
	DEVICE_TYPE_MH_AC_MOTION_3DOF_GEARS_2,	//M-Line old 3gear box simulator, not used.
	DEVICE_TYPE_MH_AC_MOTION_3DOF_GEARS_17_BIT,
	DEVICE_TYPE_MH_AC_MOTION_3DOF_2GEARS_1CYLINDER,
	DEVICE_TYPE_MH_CAC_4DOF_GEARS_KI,
	DEVICE_TYPE_MH_CAC_3DOF_TOP_KI,
	DEVICE_TYPE_MH_CAC_3DOF_BASE_KI,
	DEVICE_TYPE_MH_CAC_4DOF_TL_5MM,
	DEVICE_TYPE_MH_CAC_STEWART_PLATFORM,
	DEVICE_TYPE_EXTERNAL_MOTION,

	DEVICE_TYPE_MH_CAC_6DOF_GEARS,		//Korea airforce, 6dof
	DEVICE_TYPE_MH_CAC_3UN,
	DEVICE_TYPE_MH_CAC_4UN_VER3_B,
	DEVICE_TYPE_MH_CAC_3DOF_GEARS_400W_17,	//MLine CAC 3dof 17bit
	DEVICE_TYPE_MH_CAC_4UN_17,

	//no multiple stage device
	DEVICE_TYPE_MH_STEP_MOTION_2DOF_2U,
	DEVICE_TYPE_MH_CAC_4UN_TL_300,
	DEVICE_TYPE_MH_CAC_2AXIS_SUSPENDED_SCAFFOLD,	//QS, 2axis suspended scaffold, stroke 600mm, lead 10mm, 17bit 750w motor brake, 14bit encoder setting
	DEVICE_TYPE_MH_CAC_1DOF_FRONTIS,
	DEVICE_TYPE_MH_CAC_3DOF_5MM_ETRI,
	DEVICE_TYPE_MH_CAC_4GP,
	DEVICE_TYPE_MH_CAC_SIMG,			//Simg 3cylinder, 5mm lead, 150mm stroke
	DEVICE_TYPE_MH_TEST_MOTION,
	DEVICE_TYPE_MH_TZ_SEAT_1,
	DEVICE_TYPE_MH_TZ_SEAT_2,
	DEVICE_TYPE_MH_TZ_SEAT_3,
	DEVICE_TYPE_MH_TZ_SEAT_4,
	DEVICE_TYPE_MH_AC_MOTION_3DOF_GEARS_100_750W,
	DEVICE_TYPE_MH_CAC_3DOF_GEAR_NOVATECH,
	DEVICE_TYPE_MH_CAC_2DOF_FRONTIS,
	DEVICE_TYPE_MH_AC_MOTION_3DOF_GEARS_60_400W,
	DEVICE_TYPE_MH_SEAT_CONTROLLER,
	DEVICE_TYPE_MH_HIWIN_AC_1DOF_HYUNDAI,
	DEVICE_TYPE_MH_HIWIN_AC_3DOF_BASE_HONGIK,
	DEVICE_TYPE_MH_HIWIN_AC_4DOF_TOP_HONGIK,
	DEVICE_TYPE_MH_CAC_3DOF_5MM_MSTONE,
	DEVICE_TYPE_MH_HIWIN_AC_6DOF_GEARS,
	DEVICE_TYPE_MH_CAC_4UN_17_5,
	DEVICE_TYPE_MH_CAC_2DOF_2SEAT_A,
	DEVICE_TYPE_MH_CAC_2DOF_2SEAT_B,
	DEVICE_TYPE_MH_CAC_3DOF_GEARS_RS,	//Round star
	DEVICE_TYPE_MH_AC_MOTION_2DOFB,
	DEVICE_TYPE_MH_CAC_6AXIS_PARKS	,	//Parks Co.,Ltd 6axis, stewart platform, 300mm stroke, 5mm lead
	DEVICE_TYPE_RESERVE93	,
	DEVICE_TYPE_RESERVE94	,
	DEVICE_TYPE_RESERVE95	,
	DEVICE_TYPE_RESERVE96	,
	DEVICE_TYPE_RESERVE97	,
	DEVICE_TYPE_RESERVE98	,
	DEVICE_TYPE_RESERVE99	,
	DEVICE_TYPE_RESERVE100	,
	DEVICE_TYPE_RESERVE101	,
	DEVICE_TYPE_RESERVE102	,
	DEVICE_TYPE_RESERVE103	,
	DEVICE_TYPE_RESERVE104	,
	DEVICE_TYPE_RESERVE105	,
	DEVICE_TYPE_RESERVE106	,
	DEVICE_TYPE_RESERVE107	,
	DEVICE_TYPE_RESERVE108	,
	DEVICE_TYPE_RESERVE109	,
	DEVICE_TYPE_RESERVE110	,
	DEVICE_TYPE_RESERVE111	,
	DEVICE_TYPE_RESERVE112	,
	DEVICE_TYPE_RESERVE113	,
	DEVICE_TYPE_RESERVE114	,
	DEVICE_TYPE_RESERVE115	,
	DEVICE_TYPE_RESERVE116	,
	DEVICE_TYPE_RESERVE117	,
	DEVICE_TYPE_RESERVE118	,
	DEVICE_TYPE_RESERVE119	,
	DEVICE_TYPE_RESERVE120	,
	DEVICE_TYPE_RESERVE121	,
	DEVICE_TYPE_RESERVE122	,
	DEVICE_TYPE_RESERVE123	,
	DEVICE_TYPE_RESERVE124	,
	DEVICE_TYPE_RESERVE125	,
	DEVICE_TYPE_RESERVE126	,
	DEVICE_TYPE_RESERVE127	,
	DEVICE_TYPE_RESERVE128	,
	DEVICE_TYPE_RESERVE129	,
	DEVICE_TYPE_RESERVE130	,
	DEVICE_TYPE_RESERVE131	,
	DEVICE_TYPE_RESERVE132	,
	DEVICE_TYPE_RESERVE133	,
	DEVICE_TYPE_RESERVE134	,
	DEVICE_TYPE_RESERVE135	,
	DEVICE_TYPE_RESERVE136	,
	DEVICE_TYPE_RESERVE137	,
	DEVICE_TYPE_RESERVE138	,
	DEVICE_TYPE_RESERVE139	,
	DEVICE_TYPE_RESERVE140	,
	DEVICE_TYPE_RESERVE141	,
	DEVICE_TYPE_RESERVE142	,
	DEVICE_TYPE_RESERVE143	,
	DEVICE_TYPE_RESERVE144	,
	DEVICE_TYPE_RESERVE145	,
	DEVICE_TYPE_RESERVE146	,
	DEVICE_TYPE_RESERVE147	,
	DEVICE_TYPE_RESERVE148	,
	DEVICE_TYPE_RESERVE149	,
	DEVICE_TYPE_RESERVE150	,
	DEVICE_TYPE_MAX,
};


enum AxisSyncMode
{
	ALL_AXIS_SYNC,
	ALL_AXIS_USE_MAX_SPEED,
	ALL_AXIS_USE_SPEEDPROFILE,
};


enum USE_VIBRATION_FLAG
{
	NOT_USE_VIBRATION = 0x00,
	USE_POSITION_VIBRATION = 0x01,
};


enum USE_ACCEL_MODE
{
	USE_PREFINED_ACCEL,
	USE_FAKE_ACCEL,
};


enum AccelMapIndexUsage
{
	ACCEL_STEP_SPEED = 0,
	ACCEL_MAX_SPEED = 1,
	MAX_ACCEL_MAP_COUNT,

	FAKE_ACCEL_MAP_STEP,
	FAKE_ACCEL_MAP_MAX,
};


enum FakeAccel
{
	FAKE_ACCEL_0,
	FAKE_ACCEL_1,
	MAX_FAKE_ACCEL_COUNT,
};


enum
{
	TEST_FLAG_NONE					= 0x0,
	TEST_FLAG_MOTION_TELEMETRY		= 0x1,
	TEST_FLAG_MOTION_TARGET_POSITION= 0x2,
	TEST_FLAG_WIND_TELEMETRY		= 0x4,
	TEST_FLAG_WIND_TARGET_VALUE		= 0x8,
};


enum DriverErrorCode
{
	MOTION_DRIVER_ERROR_NO_ERROR = 0,
	MOTION_DRIVER_ERROR_CYLINDER_ERROR = 0x10,
	MOTION_DRIVER_ERROR_POWER = 0x20,
	MOTION_DRIVER_ERROR_CHANGE_SPEED_PROFILE_ERROR = 0x40,
	MOTION_DRIVER_ERROR_NO_ALIVE_PACKET = 0x80,
	MOTION_DRIVER_ERROR_CALIBRATION_ERROR = 0x100,
	MOTION_DRIVER_MOTOR_TEST_MODE = 0x200,

	PWM_DRIVER_ERROR_NO_ALIVE_PACKET = 0x400,
	MOTION_AC_DRIVER_POSITION_ERROR = 0x800,
	MOTION_AC_DRIVER_CURRENT_ERROR = 0x1000,
	MOTION_AC_DRIVER_EMERGENCY_STOP = 0x2000,

	MOTION_GROUP_ERROR = 0x3000
};


#define MIN_MAX_SPEED_STEP		300
#define MAX_MAX_SPEED_STEP		1000

#define MIN_SMOOTH_STEP			1
#define MAX_SMOOTH_STEP			20

#define MIN_ACCEL_STEP			1
#define MAX_ACCEL_STEP			20

#define MIN_VIBRATION_STEP		0
#define MAX_VIBRATION_STEP		20


enum
{
	POSITION_REQUEST_NONE = 0,

	POSITION_REQUEST_CENTER = 1,
	POSITION_REQUEST_MOVE_CENTER_DONE = 2,

	POSITION_REQUEST_BOTTOM = 3,
	POSITION_REQUEST_MOVE_BOTTOM_DONE = 4,

	POSITION_REQUEST_FAIL = 5,
};


enum
{
	INVALID_TELEMETRY = 0,
	NO_GAME_RUNNING,
	GAME_STARTED,
	GAME_RUNNING,
	GAME_STOPPED,
	GAME_PAUSED,
};


enum
{
	GAME_MANAGER_STATE_DETECT,
	GAME_MANAGER_STATE_START,
	GAME_MANAGER_STATE_PAUSING,
	GAME_MANAGER_STATE_PAUSED,
	GAME_MANAGER_STATE_RUN,
	GAME_MANAGER_STATE_STOP,
};


enum
{
	BELT_STATE_INIT = 0,
	BELT_STATE_NOT_USED = 1,
	BELT_STATE_FASTEN = 2,
	BELT_STATE_LOOSE = 3,
};


enum NetworkConnectStatus
{
	NETWORK_DISCONNECTED,
	NETWORK_CONNECTED,
};


enum MHMotionPlayerState
{
	MOTION_PLAYER_INIT,
	MOTION_PLAYER_STOPPED,
	MOTION_PLAYER_PLAYING,
	MOTION_PLAYER_PAUSED,
};


enum MHMotionPlayerReturns
{
	MHMOTION_PLAYER_LOAD_FAIL_STATE_CHECK = -20,
	MHMOTION_PLAYER_CANT_FIND_DIRECTORY = -19,
	MHMOTION_PLAYER_ALREADY_PLAYING_OTHER_FILE = -18,
	MHMOTION_PLAYER_MOTION_DATA_IS_EMPTY = -17,
	MHMOTION_PLAYER_CANT_FILE_MOTION_FILE = -16,
	MHMOTION_PLAYER_SET_PLAYPOSITION_FAILED_STATE_CHECK = -15,
	MHMOTION_PLAYER_SET_PLAYPOSITION_FAILED_INDEX_OVER = -14,
	MHMOTION_PLAYER_PLAY_FAILED_STATE_CHECK = -13,
	MHMOTION_PLAYER_SUCCESS = 0,
};


enum
{
	DCCC_STATE_NOT_USED = 0x100,
	DCCC_STATE_WAIT_COMMAND = 0,

	DCCC_STATE_MOVE_TOP_START,
	DCCC_STATE_MOVE_UNTIL_TOP_SENSOR_DETECT,
	DCCC_STATE_TOP_STOPPED,

	DCCC_STATE_MOVE_BOTTOM_START,
	DCCC_STATE_MOVE_UNTIL_BOTTOM_SENSOR_DETECT,
	DCCC_STATE_BOTTOM_STOPPED,
};


enum
{
	DCCC_COMMAND_NONE = 0,
	DCCC_COMMAND_MOVE_TOP,
	DCCC_COMMAND_MOVE_BOTTOM,
};


enum SeatAxisIndex
{
	NONE_AXIS = -1,
	SLIDE_AXIS = 0,
	RECLINE_AXIS,
	SEAT_FRONT_AXIS,
	SEAT_REAR_AXIS,
	//EXT_AXIS,
	MAX_SEAT_AXIS
};


enum AXIS_CONTROL_MODE
{
	TELEMETRY_CONTROL_MODE = 0,
	AXIS_CONTROL_MODE = 1,
	ALWAYS_CONTROL_MODE = 2,
	PRELOAD_MOTION = 3,
	AXIS_POSITION_CONTROL_MODE = 4,
};


enum
{
	TRACE_STATE_INIT = 0,
	TRACE_STATE_REQUEST_SYNC_DONE,
	TRACE_STATE_REQUEST_GET_RANGE_INFO,
	TRACE_STATE_GETTING_TRACE,
	TRACE_STATE_ERROR_OCCURED,
};

#define MHCYLINDER_MAX					8
#define MAX_BUNCH_TARGET_POSITION_COUNT 4 
#define MAX_EFFECT_INDEX				32


enum MHServicerUIEvent
{
	UI_EVENT_NONE = 0
	, UI_EVENT_START_RUMBLE_FUNCTION_VERIFICATION
};


enum MotionModeValue
{
	MOTION_MODE_INIT = -1,
	MOTION_MODE_NORMAL = 0,
	MOTION_MODE_RUMBLE,
};